# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szPersonBigName', models.CharField(db_index=True, default='\u2014', help_text='\u041f\u043e\u043b\u043e\u043d\u0435 \u0424\u0418\u041e \u043f\u0435\u0440\u0441\u043e\u043d\u044b.<br /><small><b>\u0414\u043e\u043f\u0443\u0441\u043a\u0430\u0435\u0442\u0441\u044f HTML</b>.</small>', max_length=100, unique=True, verbose_name='\u0424\u0418\u041e')),
                ('szParsonAdress', models.CharField(default='\u2014', help_text='\u0410\u0434\u0440\u0435\u0441 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f \u043f\u0435\u0440\u0441\u043e\u043d\u044b.', max_length=140, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f (\u0424\u0418\u041e, \u0430\u0434\u0440\u0435\u0441\u2026)',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0439 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438 (\u0424\u0418\u041e, \u0430\u0434\u0440\u0435\u0441\u2026)',
            },
        ),
        migrations.CreateModel(
            name='tbTelephones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szTelephoneNumber', models.CharField(default='+9(999)999-99-99', help_text='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430.<br /><small>\u0423\u0447\u0438\u0442\u044b\u0432\u0430\u044e\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e \u0446\u0438\u0444\u0440\u044b, <b>\u0432\u0441\u0435 \u043d\u0435\u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b \u043f\u0440\u0438 \u0432\u044b\u0432\u043e\u0434\u0435 \u0431\u0443\u0434\u0443\u0442 \u0443\u0434\u0430\u043b\u0435\u043d\u044b</b>. \u0423\u0432\u044b.</small>', max_length=20, verbose_name='\u0422\u0435\u043b.')),
                ('kContacts', models.ForeignKey(db_constraint=False, help_text='\u0423\u0437\u0430\u0437\u0430\u0442\u044c, \u043a\u0430\u043a\u043e\u0439 \u043f\u0435\u0440\u0441\u043e\u043d\u0435 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u0438\u0442 \u044d\u0442\u043e\u0442 \u0442\u0435\u043b\u0435\u0444\u043e\u043d.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tbContacts', verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0451\u0440')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u043d\u044b\u0435 \u043d\u043e\u043c\u0435\u0440\u0430',
            },
        ),
    ]
